excerpt_separator: ""
rouge: true
markdown: kramdown
url: http://devenv.pl
name: DevEnv
header: DevEnv
description: "DevEnv - blog techniczny"
author: Adrian Piętka & Mateusz Książek
ga_domain: auto
ga_tracking_id: "UA-70075862-2"
authors:
  apietka:
    display_name: Adrian Piętka
    github: adrianpietka
    email: adrian@pietka.me
  mksiazek:
    display_name: Mateusz Książek
    github: mejt
    email: ksiazek.mate@gmail.com
  dwrzesien:
      display_name: Dariusz Wrzesień
      github: dariuszwrzesien
      email: dariuszwrzesien@gmail.com
gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-paginate
  - jemoji
feed:
  path: atom.xml
timezone: Europe/Warsaw
collections:
  categories:
    output: true
  tags:
    output: true
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1
paginate: 10
paginate_path: "/blog:num/"
